name: Manual deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/github-actions-codepipeline
          aws-region: ${var.default_region}
      - run: aws codepipeline start-pipeline-execution --name ecs-api-cicd-pipeline 